### ISSUE TITLE
Adding a license

### ISSUE THREAD

**Issue by nk9** [meyer1994/zipwalk#4]
Hi! Thanks for this package, it was a big help in my project. Let me refactor some really hairy, annoying nested `for` loops.

Would you mind adding a license to the code? If you don't have any particular opinion, then an [MIT](https://opensource.org/licenses/?ls=mit) or Public Domain license would make it useable in the largest number of circumstances.

**Comment by meyer1994** [comment]
Hello!

Added MIT License here, https://github.com/meyer1994/zipwalk/commit/c55264090ed3a693efc1233ed2bf1c3ca6bc51a1

Will focus on your other suggestions before I create a new tag for PyPI. Also, sorry for the delay, the end of the year was busy. Hehe
