### ISSUE TITLE
Allow starting at a normal directory

### ISSUE THREAD

**Issue by nk9** [meyer1994/zipwalk#5]
It would be useful to be able to point this at a normal directory, which might or might not contain zip files, and get back file lists as you would in a normal zipwalk. So in this case:

```
/
/file.txt
/dir
/dir/archive.zip
/dir/archive.zip/nested.zip
/dir/archive.zip/nested.zip/nested.txt
/zipped_archive.zip
/zipped_archive.zip/nested_file.txt
```

I would be able to point at / and get the following results from the generator:

```
(None, [zipped_archive.zip, dir/archive.zip], [file.txt], Path(.))
(<zipped_archive.zip>, [], [nested_file.txt], Path(/zipped_archive.zip))
(<archive.zip>, [nested.zip],[], Path(/dir/archive.zip))
(<nested.zip>, [], [nested.txt], Path(/dir/archive.zip/nested.zip))
```

**Comment by meyer1994** [comment]
Interesting idea!

I am a bit confused on the behaviour you are expecting... I can see two possible behaviours:

1. When the path is a directory, keep iterating in the file tree until we find a zip file. At this point, start yielding the files like we are doing now
1. When the path is a directory, start yielding files and dirs like `os.walk` and switch to the `zipwalk` way when a zip file is found

I confess that I prefer option (1), as option (2) would require the programmer to keep checking for some flag, or type of returned value, like the `None` in your example. For example:

```py
# assuming we are doing option 2
for root, dirs, files in zipwalk(path):
    if is_zip(root):
        # zipped
    else:
        # not zipped 
```

Which, in my opinion, is not that great. One could get, if using option (1), the same behaviour without some `if/else`:

```py
for root, dirs, files in os.walk(path):
    for dir in dirs:
        for root, zips, files in zipwalk(dirs):
            # pass
```

But then we get 3 nested loops, which is not that great...

---

What do you think? Would you mind sharing a bit more about your use case? I'd love to help you.

**Comment by nk9** [comment]
Yeah, I think I've decided this isn't worth the effort. I've done 1 myself for my application, and it's straightforward enough to do. Better to allow zipwalk to always return `ZipWalkFile`s which let you get the `zpath`.
